version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile-backend
    volumes:
      - ./backend:/app
      - ./backend/db.sqlite3:/app/db.sqlite3  # Assicurati che il tuo database sia 
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile-frontend
    ports:
      - "5000:5000"
