# Usa come base l'immagine di python incantata
FROM python:3.10.12

# Imposta il direttorio di lavoro nel contenitore
WORKDIR /app

# Copia il grimorio di dipendenze
COPY requirements.txt .

# Esegui l'incantesimo per installare le dipendenze
RUN pip install --no-cache-dir -r requirements.txt

# Copia il resto del regno backend nel contenitore
COPY backend .

# Copia lo script di gestione
COPY manage_services.py .

# Dichiara la porta sulla quale il servizio sarà accessibile
EXPOSE 8000

# Il comando per avviare il regno del backend
CMD ["python", "manage_services.py"]