version: '3.7'

services:

  ccat:
    image: andrea002/ccatmysite:latest
    ports:
      - ${CORE_PORT:-1864}:80
    container_name: CCAT_mySite
    environment:
      - PYTHONUNBUFFERED=1
      - WATCHFILES_FORCE_POLLING=true
      - CORE_HOST=${CORE_HOST:-localhost}
      - CORE_PORT=${CORE_PORT:-1864}
      - CORE_USE_SECURE_PROTOCOLS=${CORE_USE_SECURE_PROTOCOLS:-}
      - API_KEY=${API_KEY:-}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - DEBUG=${DEBUG:-true}
      - SAVE_MEMORY_SNAPSHOTS=${SAVE_MEMORY_SNAPSHOTS:-true}
    command:
      - python
      - "-m"
      - "cat.main"
    restart: unless-stopped