### crea chat
POST http://localhost:8000/chat/create/
Content-Type: application/json

{
    "username": "andrea",
    "email": "nuovachat@example.com",
    "password": "password123",
    "is_superuser": false
}

### login chat
POST http://localhost:8000/chat/login/
Content-Type: application/json

{
    "email": "nuovachat@example.com",
    "password": "password123"
}


### invia messagio
POST http://localhost:8000/chat/2/messages/
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE3MjY5MjgyNDZ9.qa0GHy3SyvQxPyTyeKQZ4QlWH_m1lfcHHXu4yR6ySiU

{
    "message_text": "ciao"
}

### elimina chat
DELETE http://localhost:8000/chat/2/delete/
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE3MjY5MjgyNDZ9.qa0GHy3SyvQxPyTyeKQZ4QlWH_m1lfcHHXu4yR6ySiU


################################################# chat 2 ############################################################

### crea chat
POST http://localhost:8000/chat/create/
Content-Type: application/json

{
    "username": "Andrea Pesce",
    "email": "andrea.pesce.lavoro@gmail.com",
    "password": "0,\\a2sI6TSq1",
    "is_superuser": true
}

### login chat
POST http://localhost:8000/chat/login/
Content-Type: application/json

{
    "email": "nuovachat@exampleeee.com",
    "password": "password123"
}


### invia messagio
POST http://localhost:8000/chat/3/messages/
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE3MjY5MjgyNjl9.YQLoQZ5RJVdsTmBC0cMatKR6HjfLro7dtDNGVcnQp9U

{
    "message_text": "ciao av te"
}

### elimina chat
DELETE http://localhost:8000/chat/3/delete/
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE3MjY5MjgyNjl9.YQLoQZ5RJVdsTmBC0cMatKR6HjfLro7dtDNGVcnQp9U

### get_messaggi_connessi

GET http://localhost:8000/chat/conversations/2/3/
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE3MjY5MjgyNjl9.YQLoQZ5RJVdsTmBC0cMatKR6HjfLro7dtDNGVcnQp9U



